<a href="https://colab.research.google.com/github/HueyVault/study_NLPs/blob/main/codes/DeepLearnings/02_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### pytorch 기본

In [2]:
import torch

In [12]:
torch.device('cuda:0')

device(type='cuda', index=0)

#### torch 주요 datatype

In [13]:
x = torch.randn((10,5)) # 표준 정규 분포 N(0,1) sampling
x

tensor([[ 0.9044,  0.0245, -0.9392,  0.6500, -0.3296],
        [ 0.1819,  1.4377,  1.5246,  0.2665, -0.5444],
        [-1.0197, -0.8479,  0.4081,  1.8716, -0.1577],
        [-0.1318,  0.1025,  0.8185,  1.2870,  0.0825],
        [ 1.6147,  0.9508, -1.0703,  0.0133, -0.4046],
        [ 0.6940,  1.0002,  1.0462, -0.3869,  0.1391],
        [ 0.2938,  0.2125, -1.1288,  0.8573,  1.6193],
        [-0.7602,  0.3160, -1.2647, -0.1536, -0.0224],
        [-0.9714, -1.4186,  0.1515,  1.2175,  1.1716],
        [ 0.1532,  0.6679,  0.0919,  1.8284, -0.5135]])

In [14]:
type(x), x.dtype, x.shape, x.device, x.size() # 항상 float으로, #device(type='cpu') CPU DRAM 사용중

(torch.Tensor,
 torch.float32,
 torch.Size([10, 5]),
 device(type='cpu'),
 torch.Size([10, 5]))

In [15]:
x[0]

tensor([ 0.9044,  0.0245, -0.9392,  0.6500, -0.3296])

In [16]:
# gpu인 cuda 사용
x_cuda = x.to('cuda') # GPU HBM 영역으로 변경 , device='cuda:0')
x_cuda

tensor([[ 0.9044,  0.0245, -0.9392,  0.6500, -0.3296],
        [ 0.1819,  1.4377,  1.5246,  0.2665, -0.5444],
        [-1.0197, -0.8479,  0.4081,  1.8716, -0.1577],
        [-0.1318,  0.1025,  0.8185,  1.2870,  0.0825],
        [ 1.6147,  0.9508, -1.0703,  0.0133, -0.4046],
        [ 0.6940,  1.0002,  1.0462, -0.3869,  0.1391],
        [ 0.2938,  0.2125, -1.1288,  0.8573,  1.6193],
        [-0.7602,  0.3160, -1.2647, -0.1536, -0.0224],
        [-0.9714, -1.4186,  0.1515,  1.2175,  1.1716],
        [ 0.1532,  0.6679,  0.0919,  1.8284, -0.5135]], device='cuda:0')

In [17]:
type(x_cuda), x_cuda.dtype, x_cuda.shape, x_cuda.device # device(type='cuda', index=0))

(torch.Tensor,
 torch.float32,
 torch.Size([10, 5]),
 device(type='cuda', index=0))

In [19]:
# x + x_cuda # RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
x.cuda() + x_cuda

tensor([[ 1.8088,  0.0490, -1.8785,  1.3001, -0.6592],
        [ 0.3638,  2.8755,  3.0491,  0.5331, -1.0889],
        [-2.0393, -1.6958,  0.8162,  3.7432, -0.3154],
        [-0.2636,  0.2050,  1.6369,  2.5741,  0.1651],
        [ 3.2294,  1.9016, -2.1405,  0.0266, -0.8091],
        [ 1.3880,  2.0003,  2.0925, -0.7738,  0.2782],
        [ 0.5877,  0.4249, -2.2575,  1.7145,  3.2386],
        [-1.5205,  0.6320, -2.5294, -0.3072, -0.0448],
        [-1.9428, -2.8373,  0.3030,  2.4349,  2.3432],
        [ 0.3064,  1.3358,  0.1838,  3.6568, -1.0269]], device='cuda:0')

In [20]:
x_cuda.T.shape # 행 열 변환

torch.Size([5, 10])

In [21]:
x_temp = x_cuda @ x_cuda.T # [10,5] @ [5,10] = [10,10]
x_temp, x_temp.shape

(tensor([[ 2.2319, -0.8795, -0.0577, -0.0760,  2.6309, -0.6278,  1.3546,  0.4156,
          -0.6504,  1.4264],
         [-0.8795,  4.7919, -0.1976,  1.6693,  0.2528,  2.9804, -2.0151, -1.6408,
          -2.2987,  1.8951],
         [-0.0577, -0.1976,  5.4531,  2.7773, -2.8007, -1.8748,  0.4087, -0.2928,
           4.3491,  2.8181],
         [-0.0760,  1.6693,  2.7773,  2.3610, -1.0076,  0.3809,  0.2962, -1.1021,
           1.7702,  2.4343],
         [ 2.6309,  0.2528, -2.8007, -1.0076,  4.8206,  0.8903,  1.2408,  0.4334,
          -3.5373,  1.0161],
         [-0.6278,  2.9804, -1.8748,  0.3809,  0.8903,  2.7456, -0.8710, -1.4784,
          -2.2425,  0.0916],
         [ 1.3546, -2.0151,  0.4087,  0.2962,  1.2408, -0.8710,  4.7626,  1.1034,
           2.1830,  0.8192],
         [ 0.4156, -1.6408, -0.2928, -1.1021,  0.4334, -1.4784,  1.1034,  2.3014,
          -0.1146, -0.2909],
         [-0.6504, -2.2987,  4.3491,  1.7702, -3.5373, -2.2425,  2.1830, -0.1146,
           5.8340,  0.5420],
 